markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
sass:
  style: :compressed

theme: jekyll-theme-slate
defaults:
  -
    scope:
      path: "stages"
    values:
      layout: "stage"
